version: '3'
services:
  database:
    container_name: database
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "${DB_EXPOSE_PORT}:5432"

  cache:
    container_name: cache
    image: "redis:alpine"
    volumes:
      - cache-data:/data
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    networks:
      - app-network
    ports:
      - "${BACKEND_EXPOSE_PORT}:80"
    volumes:
      - ./backend/src:/app/src
    restart: on-failure
    depends_on:
      - database
      - cache
    

networks:
  app-network:
    name: ${NETWORK_NAME:+parkour-net}
    driver: bridge

volumes:
  db-data: 
  cache-data: